name: deliciouseats-backend-laravel
type: php

build:
  command: |
    composer install --optimize-autoloader --no-dev
    php artisan config:cache
    php artisan route:cache
    php artisan view:cache
    # Temporarily comment out migration to prevent deployment failure
    # php artisan migrate --force

start:
  command: php artisan serve --host=0.0.0.0 --port=8080

env:
  APP_ENV: production
  APP_DEBUG: false
  APP_URL: https://deliciouseats-backend-laravel.pxxl.xyz